import { assertEquals } from "jsr:@std/assert";

import { solve } from "./solver.ts";

const testInput = `............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............`;

Deno.test("day 08", () => {
	assertEquals(solve(testInput), 14);
});
